"""empty message

Revision ID: 82cd5036eb92
Revises: b08a27f7d731
Create Date: 2020-05-10 10:07:48.428385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cd5036eb92'
down_revision = 'b08a27f7d731'
branch_labels = None
depends_on = None


def upgrade():
    # renaming tables
    op.execute('alter table "Venue" rename to venues')
    op.execute('alter table "Artist" rename to artists')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
